import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { solid, regular, brands } from '@fortawesome/fontawesome-svg-core/import.macro';

import fontawesome from '@fortawesome/fontawesome'
import {
  faBandage,
  faBiohazard,
  faBug,
  faCircle,
  faCircleDot,
  faCirclePlay,
  faCubes,
  faDoorClosed,
  faElevator,
  faExclamationTriangle,
  faFire,
  faFireExtinguisher,
  faHeadset,
  faImage,
  faLocationDot,
  faMessage,
  faPen,
  faPerson,
  faRadiation,
  faRightFromBracket,
  faSignsPost,
  faSkull,
  faSquare,
  faStairs,
  faTruckMedical,
  faUser,
  faRobot,
  faMobileScreenButton,
  faLaptopCode
} from "@fortawesome/free-solid-svg-icons";

fontawesome.library.add(
  faBandage,
  faBiohazard,
  faBug,
  faCircle,
  faCircleDot,
  faCirclePlay,
  faCubes,
  faDoorClosed,
  faElevator,
  faExclamationTriangle,
  faFire,
  faFireExtinguisher,
  faHeadset,
  faImage,
  faLocationDot,
  faMessage,
  faPen,
  faPerson,
  faRadiation,
  faRightFromBracket,
  faSignsPost,
  faSkull,
  faSquare,
  faStairs,
  faTruckMedical,
  faUser,
  faRobot,
  faMobileScreenButton,
  faLaptopCode
  );

// Map feature type -> FA icon
const IconMap = {
  '3d-map': solid('cubes'),
  ambulance: solid('truck-medical'),
  audio: solid('circle-play'),
  'bad-person': solid('skull'),
  biohazard: solid('biohazard'),
  'ceiling-sign': solid('signs-post'),
  door: solid('door-closed'),
  editor: solid('laptop-code'),
  elevator: solid('elevator'),
  exit: solid('right-from-bracket'),
  extinguisher: solid('fire-extinguisher'),
  fire: solid('fire'),
  headset: solid('headset'),
  injury: solid('bandage'),
  message: solid('message'),
  object: solid('square'),
  person: solid('person'),
  phone: solid('mobile-screen-button'),
  photo: solid('image'),
  point: solid('circle'),
  radiation: solid('radiation'),
  robot: solid('robot'),
  stairs: solid('stairs'),
  target: solid('circle-dot'),
  user: solid('user'),
  'wall-sign': solid('signs-post'),
  warning: solid('triangle-exclamation'),
  waypoint: solid('location-dot'),
};

export default IconMap;
