name: easyvizar-edge-server
description: Collaboration point for multiple EasyVizAR headsets
version: 1

services:
  main:
    command: python3 -m server
    image: python3
    source: .
    type: light
    environment:
      APPLICATION_CONFIG: ../app.conf
      QUART_APP: server.main:app
      QUART_ENV: production
      VIZAR_HOST: 0.0.0.0
      VIZAR_PORT: 5000

web:
  port: 5000
  service: main
