name: easyvizar-edge
base: core20
version: "0.1"
summary: Central point for coordinating EasyVizAR headsets
description: |
  This module coordinates interactions between multiple AR headsets, collects
  map and position changes from them, and disseminates important updates to all
  of the headsets. The primary functionality is exposed through an HTTP-based
  API and web interface.

grade: stable
confinement: strict

apps:
  server:
    command: bin/server
    daemon: simple
    environment:
      APPLICATION_CONFIG: $SNAP_DATA/server.conf
      LD_PRELOAD: $SNAP/usr/lib/libsnapcraft-preload.so
      VIZAR_DATA_DIR: $SNAP_DATA
      VIZAR_STATIC_FOLDER: $SNAP/frontend/build
      VIZAR_HOST: 0.0.0.0
    plugs:
      - network
      - network-bind

hooks:
  configure:
    plugs: []

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - on amd64:
        - lib32stdc++6

  frontend:
    plugin: nil
    source: server/frontend
    build-packages:
      - npm
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/frontend
      cp -rv build $SNAPCRAFT_PART_INSTALL/frontend/

  server:
    plugin: python
    source: .
    build-packages:
      - libffi-dev
      - libjpeg-dev
      - python3-dev
    stage-packages:
      - libcairo2
      - libjpeg-turbo8
      - python3
    requirements:
      - requirements.txt

# The read-only data slot allows other snaps on the system to read the
# VIZAR_DATA directory directly. This may be useful for image processing
# modules. Changes should go through the API.
slots:
  data:
    interface: content
    content: data
    read:
      - $SNAP_DATA
